import os
import sys
import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces
import torch

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

try:
    from nlp.gamma_pipeline import load_siglip, encode_image
    SIGLIP_AVAILABLE = True
except ImportError as e:
    SIGLIP_AVAILABLE = False
    print(f"[Gamma Wrapper] WARNING: Could not import gamma_pipeline. Details: {e}")


class GammaLanguageConditionedWrapper(gym.ObservationWrapper):
    """
    Gamma version of LanguageConditionedWrapper.
    Replaces ResNet18 (512,) + physics (9,) + MiniLM (384,) with:
        vision: SigLIP vision encoder → (768,)
        nlp:    SigLIP text encoder   → (768,)
    No separate physics state — SigLIP vision handles the full image.
    """

    def __init__(self, env):
        super().__init__(env)

        # Gamma observation space: both branches are 768-dim
        self.observation_space = spaces.Dict({
            'vision': spaces.Box(low=-np.inf, high=np.inf, shape=(768,), dtype=np.float32),
            'nlp':    spaces.Box(low=-1.0,    high=1.0,    shape=(768,), dtype=np.float32)
        })

        # Load SigLIP once at startup
        if SIGLIP_AVAILABLE:
            self.siglip_model, self.siglip_processor, self.siglip_device = load_siglip()
        else:
            self.siglip_model = self.siglip_processor = self.siglip_device = None

        # Load pre-encoded instruction embeddings (768-dim, generated by gamma_pipeline)
        self.nlp_base_path = os.path.abspath(os.path.join(
            os.path.dirname(__file__), '..', 'nlp'
        ))
        self._load_nlp_dataset()

        self.current_instruction_idx = 0
        self.current_embedding = np.zeros(768, dtype=np.float32)
        self.current_instruction = ""

    def _load_nlp_dataset(self):
        npy_path = os.path.join(self.nlp_base_path, 'embeddings_gamma_768.npy')
        csv_path = os.path.join(self.nlp_base_path, 'nlp_instructions.csv')

        if os.path.exists(npy_path) and os.path.exists(csv_path):
            self.embeddings = np.load(npy_path).astype(np.float32)
            self.instructions_df = pd.read_csv(csv_path)
            self.num_instructions = len(self.embeddings)
            print(f"[Gamma Wrapper] Loaded {self.num_instructions} SigLIP embeddings (768-dim)")
        else:
            print("[Gamma Wrapper] WARNING: embeddings_gamma_768.npy not found. Using mock embeddings.")
            self.embeddings = np.random.uniform(-1, 1, size=(340, 768)).astype(np.float32)
            self.num_instructions = 340
            self.instructions_df = None

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)

        # Sample a new random instruction each episode
        self.current_instruction_idx = np.random.randint(0, self.num_instructions)
        self.current_embedding = self.embeddings[self.current_instruction_idx]

        if self.instructions_df is not None:
            self.current_instruction = self.instructions_df.iloc[self.current_instruction_idx]['instruction']
            info['current_instruction'] = self.current_instruction

        return self.observation(obs), info

    def observation(self, obs):
        raw_pixels = obs['pixels']  # (H, W, 3) from PyBullet

        if SIGLIP_AVAILABLE and self.siglip_model is not None:
            vision_feat = encode_image(
                raw_pixels,
                self.siglip_model,
                self.siglip_processor,
                self.siglip_device
            )  # (768,) L2-normalized
        else:
            # Fallback: random normalized vector
            v = np.random.randn(768).astype(np.float32)
            vision_feat = (v / np.linalg.norm(v))

        return {
            'vision': vision_feat.astype(np.float32),   # (768,)
            'nlp':    self.current_embedding              # (768,)
        }